SELECT COLUMN_NAME+'; ;'+DATA_TYPE+';0;' as Kolommen
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GEOLOGISCHE_KAART' and COLUMN_NAME not like 'OBJECTID' and COLUMN_NAME not like 'Shape' and COLUMN_NAME not like 'GDB_GEOMATTR_DATA' 
ORDER BY ORDINAL_POSITION
